import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Layout from '../../components/Layout'
import type { Character, EquipmentEntry } from '../../lib/types'
import { CHARACTERISTICS, SKILLS } from '../../lib/types'
import { loadCharacter, saveCharacter, deleteCharacter } from '../../lib/storage'
import { EQUIPMENT } from '../../data/equipment'
import { WEAPON_ACTIONS } from '../../data/weaponPresentation'
const numberOr=(v:string,f:number)=>{const n=Number(v);return Number.isFinite(n)?n:f}
const skillForCheck=(c:string)=>/Light Ranged/i.test(c)?{characteristic:'Agility' as const,skill:'Weapon, Light Ranged' as const}:/Heavy Ranged/i.test(c)?{characteristic:'Agility' as const,skill:'Weapon, Heavy Ranged' as const}:/Light Melee/i.test(c)?{characteristic:'Hardiness' as const,skill:'Weapon, Light Melee' as const}:/Heavy Melee/i.test(c)?{characteristic:'Hardiness' as const,skill:'Weapon, Heavy Melee' as const}:/Unarmed/i.test(c)?{characteristic:'Hardiness' as const,skill:'Weapon, Unarmed' as const}:null
const defaultAttackCheck=(name:string,details:string)=>{const a=WEAPON_ACTIONS[name]?.find(x=>/single shot|^shot$/i.test(x.title))||WEAPON_ACTIONS[name]?.[0];return a?.check||details.split(';').map(x=>x.trim()).find(x=>/Weapon,|^\d+d\d+/i.test(x))||''}
const magazineCapacity=(d:string)=>{const m=d.split(';').map(x=>x.trim()).find(x=>/^magazine\b/i.test(x));if(!m)return null;const n=Number(m.replace(/^magazine\s*/i,''));return Number.isFinite(n)?n:null}
const ammoUsed=(title:string,effect?:string)=>/suppress/i.test(title)?Number(effect?.match(/uses\s+(\d+)\s+ammunition/i)?.[1]||1):/burst/i.test(title)?3:1
const armourStats=(details:string)=>{const a=Number(details.match(/Armour\s+(\d+)/i)?.[1]||0);const t=details.match(/Threshold\s+(\d+)P,\s*(\d+)E/i);return{armour:a,physical:Number(t?.[1]||0),energy:Number(t?.[2]||0)}}
export default function Active(){
 const r=useRouter();const[c,setC]=useState<Character|null>(null);const[tab,setTab]=useState<'overview'|'skills'|'inventory'>('overview');const[condition,setCondition]=useState('')
 useEffect(()=>{if(r.isReady)loadCharacter(String(r.query.id)).then(setC)},[r.isReady,r.query.id]);if(!c)return <Layout><div className="panel">LOADING CHARACTER...</div></Layout>
 const save=(n:Character)=>{setC(n);void saveCharacter(n)}
 const setStam=(v:number)=>save({...c,currentStamina:Math.max(0,Math.min(c.stamina,v))})
 const setMaxStam=(v:number)=>{const n=Math.max(0,v);save({...c,stamina:n,currentStamina:Math.min(c.currentStamina,n)})}
 const setLuck=(v:number)=>save({...c,luck:Math.max(0,Math.min(6,v))})
 const setSpeed=(v:number)=>save({...c,speed:Math.max(0,v)})
 const setCharacteristic=(n:typeof CHARACTERISTICS[number],v:number)=>save({...c,characteristics:{...c.characteristics,[n]:v}})
 const setSkill=(n:typeof SKILLS[number],v:number)=>save({...c,skills:{...c.skills,[n]:Math.max(0,Math.min(5,v))}})
 const armourItems=c.equipment.filter(e=>EQUIPMENT.find(x=>x.name===e.name)?.category==='Armour');const armourName=armourItems.some(e=>e.name===c.armourName)?c.armourName!:armourItems[0]?.name||''
 const selectArmour=(name:string)=>{const e=armourItems.find(x=>x.name===name),d=EQUIPMENT.find(x=>x.name===name);if(!e||!d)return;const s=armourStats(d.details);save({...c,armourName:name,armourValue:s.armour,thresholdPhysical:s.physical,thresholdEnergy:s.energy})}
 const setArmour=(v:number)=>save({...c,armourValue:Math.max(0,v)})
 const setThreshold=(kind:'physical'|'energy',v:number)=>save({...c,[kind==='physical'?'thresholdPhysical':'thresholdEnergy']:Math.max(0,v)})
 const rollAttack=(check:string,label:string,index?:number,uses=1)=>{const p=skillForCheck(check);if(!p)return;const e=index===undefined?null:c.equipment[index];const cap=e?magazineCapacity(e.details??EQUIPMENT.find(x=>x.name===e.name)?.details??''):null;let remaining:number|undefined;if(e&&cap!==null){const cur=e.currentMagazine??cap;if(cur<uses){window.alert(`${label}\n\nNot enough ammunition.\nCurrent magazine: ${cur}/${cap}`);return}remaining=cur-uses;save({...c,equipment:c.equipment.map((x,i)=>i===index?{...x,currentMagazine:remaining}:x)})}const ch=c.characteristics[p.characteristic],sk=c.skills[p.skill],d1=Math.floor(Math.random()*10)+1,d2=Math.floor(Math.random()*10)+1;window.alert(`${label}\n\n2d10: ${d1} + ${d2}\n${p.characteristic}: +${ch}\n${p.skill}: +${sk}${remaining!==undefined?`\nAmmunition used: ${uses}\nMagazine remaining: ${remaining}`:''}\n\nTotal: ${d1+d2+ch+sk}`)}
 const addEquipment=(name:string)=>{const x=EQUIPMENT.find(e=>e.name===name);if(!x||x.cost===null)return;const cap=magazineCapacity(x.details);save({...c,equipment:[...c.equipment,{id:crypto.randomUUID(),name:x.name,quantity:1,cost:x.cost,properties:x.properties||'—',rarity:x.rarity,carry:x.carry,details:x.details,...(cap!==null?{currentMagazine:cap}:{})}]})};const updateEquipment=(i:number,p:Partial<EquipmentEntry>)=>save({...c,equipment:c.equipment.map((e,n)=>n===i?{...e,...p}:e)});const removeEquipment=(i:number)=>save({...c,equipment:c.equipment.filter((_,n)=>n!==i)});const removeCharacter=async()=>{if(window.confirm(`Delete ${c.name||'this character'} permanently?`)){await deleteCharacter(c.id);await r.push('/')}};const portrait=(file:File|null)=>{if(!file)return;const fr=new FileReader();fr.onload=()=>save({...c,portrait:String(fr.result)});fr.readAsDataURL(file)}
 const renderDetails=(e:EquipmentEntry,i:number,d:{category:string;details:string})=>{const details=e.details??d.details,actions=WEAPON_ACTIONS[e.name],parts=details.split(';').map(x=>x.trim()).filter(Boolean),range=parts.find(x=>/^\d+(?:\.\d+)?m\b|^\d+\s*cube/i.test(x)),combat=parts.find(x=>/Weapon,|^\d+d\d+/i.test(x)),ammo=parts.find(x=>/Cr\/shot/i.test(x)),mag=parts.find(x=>/^magazine\b/i.test(x)),cap=magazineCapacity(details),cur=cap===null?null:e.currentMagazine??cap;if(actions)return <div className="equipmentDetails">{actions.map(a=><div className="equipmentAction" key={a.title}><h4><button className="attackActionButton" onClick={()=>a.check&&rollAttack(a.check,`${e.name} — ${a.title}`,i,ammoUsed(a.title,a.effect))}>{a.title}</button></h4><div className="equipmentMeta">📐 {a.range} &nbsp;&nbsp;🎯 {a.target}</div>{a.check&&<button className="equipmentRule attackCheckButton" onClick={()=>rollAttack(a.check!,`${e.name} — ${a.title}`,i,ammoUsed(a.title,a.effect))}><strong>{a.check.replace(/Weapon, /,'Weapons, ')}</strong></button>}{a.tiers&&<ul className="equipmentTiers">{a.tiers.map(t=><li key={t}>{t}</li>)}</ul>}{a.effect&&<div className="equipmentRule"><strong>Effect:</strong> {a.effect}</div>}</div>)}{ammo&&<div className="equipmentRule"><strong>Ammunition Cost:</strong> {ammo}</div>}{mag&&<div className="equipmentRule"><strong>Magazine:</strong> {mag.replace(/^magazine\s*/i,'')}</div>}{cap!==null&&<label className="equipmentRule"><strong>Current Magazine:</strong><input type="number" min={0} max={cap} value={cur??''} onChange={x=>updateEquipment(i,{currentMagazine:Math.max(0,Math.min(cap,numberOr(x.target.value,cur??cap)))})}/></label>}</div>;return <div className="equipmentDetails">{range&&<div className="equipmentMeta">📐 {range} &nbsp;&nbsp;🎯 {/cube|area/i.test(range)?'All creatures in the area':'One creature or object'}</div>}{combat&&<button className="equipmentRule attackCheckButton" onClick={()=>rollAttack(combat,`${e.name} — Single Shot`,i)}><strong>{combat.replace(/Weapon, /,'Weapons, ')}</strong></button>}{parts.filter(x=>/^(Armour|Threshold|Aim|Reset|Effect|Special|Surgery|Location|Side effect)/i.test(x)).map(x=><div className="equipmentRule" key={x}>{x}</div>)}{ammo&&<div className="equipmentRule"><strong>Ammunition Cost:</strong> {ammo}</div>}{mag&&<div className="equipmentRule"><strong>Magazine:</strong> {mag.replace(/^magazine\s*/i,'')}</div>}{cap!==null&&<label className="equipmentRule"><strong>Current Magazine:</strong><input type="number" min={0} max={cap} value={cur??''} onChange={x=>updateEquipment(i,{currentMagazine:Math.max(0,Math.min(cap,numberOr(x.target.value,cur??cap)))})}/></label>}</div>}
 return <><style jsx global>{`.hudTop{display:grid;grid-template-columns:1.35fr 2fr 1fr 1fr;gap:1px;background:var(--border);margin-bottom:1px;border:1px solid var(--border)}.hudStat{background:linear-gradient(180deg,#111d2a,#0a121b);padding:14px;min-height:112px;position:relative}.hudStat>span,.characteristicsRow span{display:block;color:var(--muted);font-family:'Orbitron',sans-serif;font-size:8px;letter-spacing:1.5px}.hudStat input,.hudStat select{width:100%;margin-top:7px;background:#080d14;border:1px solid #2a3d54;color:white;border-radius:3px;padding:7px 8px;font-family:'Rajdhani',sans-serif}.hudEditPair{display:flex;align-items:center;gap:5px}.hudEditPair input{font-size:22px;text-align:center;font-family:'Orbitron',sans-serif;color:var(--blue-bright)}.hudEditPair em{font-style:normal;color:var(--muted)}.staminaStat>input[type=range]{accent-color:var(--blue);padding:0;border:0;background:none}.hudTriple{display:grid;grid-template-columns:1fr 1fr 1fr;gap:6px;margin-top:6px}.hudTriple label{margin:0;color:var(--muted);font-family:'Orbitron',sans-serif;font-size:7px;letter-spacing:1px}.hudTriple input{font-size:18px;text-align:center;color:var(--blue-bright);font-family:'Orbitron',sans-serif}.hudBigInput{font-size:30px!important;text-align:center;color:var(--blue-bright)!important;font-family:'Orbitron',sans-serif!important}.speedInput{display:flex;align-items:center;gap:6px}.speedInput small{color:var(--muted);font-family:'Orbitron',sans-serif}.characteristicsRow{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;background:var(--border);border:1px solid var(--border);border-top:0;margin-bottom:18px}.characteristicsRow label{background:linear-gradient(180deg,#111d2a,#0a121b);padding:10px 12px}.characteristicsRow input{display:block;width:100%;margin-top:6px;background:#080d14;border:1px solid #2a3d54;color:var(--blue-bright);border-radius:3px;padding:7px;text-align:center;font:600 20px 'Orbitron',sans-serif}.characteristicsRow input:focus,.hudStat input:focus,.hudStat select:focus{border-color:var(--blue-bright);outline:none;box-shadow:0 0 12px rgba(60,150,220,.17)}@media(max-width:1050px){.hudTop{grid-template-columns:1fr 1.5fr 1fr 1fr}.characteristicsRow{grid-template-columns:repeat(3,1fr)}}@media(max-width:700px){.hudTop,.characteristicsRow{grid-template-columns:1fr}.hudTriple{grid-template-columns:repeat(3,1fr)}}`}</style><Layout><div className="activeTop"><div><div className="eyebrow">ACTIVE PERSONNEL</div><h1>{c.name||'UNNAMED'}</h1></div><div className="row"><span className="save">● AUTOSAVED</span><button className="danger" onClick={removeCharacter}>DELETE CHARACTER</button></div></div>
 <div className="hudTop"><div className="hudStat staminaStat"><span>STAMINA</span><div className="hudEditPair"><input type="number" min={0} value={c.currentStamina} onChange={e=>setStam(numberOr(e.target.value,c.currentStamina))}/><em>/</em><input type="number" min={0} value={c.stamina} onChange={e=>setMaxStam(numberOr(e.target.value,c.stamina))}/></div><input type="range" min={0} max={c.stamina} value={Math.min(c.currentStamina,c.stamina)} onChange={e=>setStam(Number(e.target.value))}/></div>
 <div className="hudStat armourStat"><span>ARMOUR</span>{armourItems.length?<select value={armourName} onChange={e=>selectArmour(e.target.value)}>{armourItems.map(e=><option key={e.id} value={e.name}>{e.name}</option>)}</select>:<div className="muted">NO ARMOUR</div>}<div className="hudTriple"><label>ARMOUR<input type="number" min={0} value={c.armourValue??0} onChange={e=>setArmour(numberOr(e.target.value,0))}/></label><label>PHYSICAL<input type="number" min={0} value={c.thresholdPhysical??0} onChange={e=>setThreshold('physical',numberOr(e.target.value,0))}/></label><label>ENERGY<input type="number" min={0} value={c.thresholdEnergy??0} onChange={e=>setThreshold('energy',numberOr(e.target.value,0))}/></label></div></div>
 <div className="hudStat"><span>LUCK</span><input className="hudBigInput" type="number" min={0} max={6} value={c.luck} onChange={e=>setLuck(numberOr(e.target.value,c.luck))}/></div>
 <div className="hudStat"><span>SPEED</span><div className="speedInput"><input className="hudBigInput" type="number" min={0} value={c.speed} onChange={e=>setSpeed(numberOr(e.target.value,c.speed))}/><small>m</small></div></div></div>
 <div className="characteristicsRow">{CHARACTERISTICS.map(x=><label key={x}><span>{x.toUpperCase()}</span><input type="number" value={c.characteristics[x]} onChange={e=>setCharacteristic(x,numberOr(e.target.value,0))}/></label>)}</div>
 <div className="tabs">{(['overview','skills','inventory'] as const).map(t=><button key={t} className={tab===t?'activeTab':''} onClick={()=>setTab(t)}>{t.toUpperCase()}</button>)}</div>
 {tab==='overview'&&<div className="grid three"><section className="panel"><h2>CHARACTER PORTRAIT</h2>{c.portrait?<img src={c.portrait} alt="Character portrait" style={{width:'100%',maxHeight:320,objectFit:'cover'}}/>:<p className="muted">No portrait uploaded.</p>}<label>UPLOAD PORTRAIT<input type="file" accept="image/*" onChange={e=>portrait(e.target.files?.[0]||null)}/></label>{c.portrait&&<button className="secondary" onClick={()=>save({...c,portrait:undefined})}>REMOVE PORTRAIT</button>}</section><section className="panel"><h2>RESOURCES</h2><label>CREDITS<input type="number" min={0} value={c.credits} onChange={e=>save({...c,credits:Math.max(0,numberOr(e.target.value,0))})}/></label><label>IMPROVEMENT POINTS<input type="number" min={0} value={c.improvementPoints} onChange={e=>save({...c,improvementPoints:Math.max(0,numberOr(e.target.value,0))})}/></label></section><section className="panel"><h2>CONDITIONS / NOTES</h2><div className="row"><input value={condition} onChange={e=>setCondition(e.target.value)} placeholder="Add note or condition"/><button onClick={()=>setCondition('')}>CLEAR</button></div>{condition&&<p>{condition}</p>}</section></div>}
 {tab==='skills'&&<section className="panel"><h2>SKILLS</h2><div className="skillsEditable">{SKILLS.map(s=><label className="skillEdit" key={s}><span>{s}</span><input type="number" min={0} max={5} value={c.skills[s]} onChange={e=>setSkill(s,numberOr(e.target.value,0))}/></label>)}</div></section>}
 {tab==='inventory'&&<section className="panel"><div className="inventory-head"><h2>INVENTORY</h2><select defaultValue="" onChange={e=>{if(e.target.value){addEquipment(e.target.value);e.currentTarget.value=''}}}><option value="">ADD EQUIPMENT...</option>{EQUIPMENT.map(x=><option key={x.name} value={x.name} disabled={x.cost===null}>{x.name}</option>)}</select></div><div className="equipmentGrid">{c.equipment.length===0?<p className="muted">No equipment recorded.</p>:c.equipment.map((item,i)=>{const d=EQUIPMENT.find(x=>x.name===item.name);if(!d)return null;const check=defaultAttackCheck(item.name,item.details??d.details);return <article className="equipmentCard" key={item.id}><div className="equipmentCardHeader"><button className="equipmentNameButton" onClick={()=>check&&rollAttack(check,`${item.name} — Single Shot`,i)}>{item.name}</button><input className="equipmentNameInput" value={item.name} onChange={e=>updateEquipment(i,{name:e.target.value})}/><button className="danger" onClick={()=>removeEquipment(i)}>REMOVE</button></div><div className="equipmentDivider"/><div className="equipmentFields"><label><strong>Properties:</strong><input value={item.properties??d.properties??'—'} onChange={e=>updateEquipment(i,{properties:e.target.value})}/></label><label><strong>Cost:</strong><input type="number" min={0} value={item.cost} onChange={e=>updateEquipment(i,{cost:Math.max(0,numberOr(e.target.value,item.cost))})}/></label><label><strong>Rarity:</strong><input type="number" min={0} max={6} value={item.rarity??''} onChange={e=>updateEquipment(i,{rarity:e.target.value===''?null:numberOr(e.target.value,0)})}/></label><label><strong>Carry Capacity:</strong><input value={item.carry??d.carry} onChange={e=>updateEquipment(i,{carry:e.target.value})}/></label></div>{renderDetails(item,i,d)}<div className="equipmentQuantity"><span>QUANTITY</span><button onClick={()=>updateEquipment(i,{quantity:Math.max(1,item.quantity-1)})}>−</button><input type="number" min={1} value={item.quantity} onChange={e=>updateEquipment(i,{quantity:Math.max(1,numberOr(e.target.value,1))})}/><button onClick={()=>updateEquipment(i,{quantity:item.quantity+1})}>+</button></div></article>})}</div></section>}</Layout></>
}