import {useState} from 'react'; import {useRouter} from 'next/router'; import Layout from '../../components/Layout'; import {newCharacter,recalc,characteristicTotal,creationSkillRequirementOk} from '../../lib/rules'; import {CHARACTERISTICS,SKILLS,type Characteristic,type SkillName} from '../../lib/types'; import {saveCharacter} from '../../lib/storage'; import {EQUIPMENT} from '../../data/equipment';
export default function Create(){const r=useRouter();const [c,setC]=useState(newCharacter());const [step,setStep]=useState(0);const [pool,setPool]=useState<number|null>(null);const [startingMoney,setStartingMoney]=useState<number|null>(null);const [search,setSearch]=useState('');const [popup,setPopup]=useState<{title:string;body:string}|null>(null);
const total=characteristicTotal(c.characteristics);const extra=Math.max(0,6-total);const skillVals=Object.values(c.skills);const at2=skillVals.filter(v=>v===2).length;const at3=skillVals.filter(v=>v===3).length;const at1=skillVals.filter(v=>v===1).length;const skillValid=creationSkillRequirementOk(c);
const equip=EQUIPMENT.filter(e=>e.name.toLowerCase().includes(search.toLowerCase())&&e.cost!==null&&e.rarity!==null&&e.rarity<=3);
function update(next:any){setC(recalc(next))}
function roll(){setPool(Math.floor(Math.random()*6)+1);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function take4(){setPool(4);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function dist(k:Characteristic,d:number){const v=c.characteristics[k];const sum=characteristicTotal(c.characteristics);if(d>0&&(pool===null||sum>=pool||v>=2))return;if(d<0&&v<=0)return;update({...c,characteristics:{...c.characteristics,[k]:v+d}})}
function setSkill(s:SkillName,v:number){update({...c,skills:{...c.skills,[s]:Math.max(0,Math.min(5,v))}})}
function addEquipment(name:string){const e=EQUIPMENT.find(x=>x.name===name);if(!e||e.cost===null)return;if(c.equipmentCredits<e.cost)return;update({...c,equipmentCredits:c.equipmentCredits-e.cost,equipment:[...c.equipment,{id:crypto.randomUUID(),name:e.name,quantity:1,cost:e.cost}]})}
function undoEquipment(id:string){const item=c.equipment.find(e=>e.id===id);if(!item)return;update({...c,equipmentCredits:c.equipmentCredits+item.cost,equipment:c.equipment.filter(e=>e.id!==id)})}
function continueSkills(){if(skillValid){setStep(3);return}const problems:string[]=[];if(at2!==5)problems.push(`You need exactly 5 skills at 2 (currently ${at2}).`);if(at3!==1+extra)problems.push(`You need exactly ${1+extra} skill${1+extra===1?'':'s'} at 3 (currently ${at3}).`);if(at1!==1)problems.push(`You need exactly 1 skill at 1 (currently ${at1}).`);setPopup({title:'SKILL SELECTION INCOMPLETE',body:problems.join('\n')});}
function continueCharacteristics(){if(pool!==null&&total===pool){setStep(2);return}setPopup({title:'CHARACTERISTICS INCOMPLETE',body:pool===null?'Roll the D6 or choose TAKE 4 before continuing.':`You must allocate the entire pool. Pool: ${pool}. Allocated: ${total}.`});}
function finish(){if(startingMoney===null)return;const final={...c,currentStamina:c.stamina,credits:startingMoney+c.equipmentCredits};saveCharacter(final).then(()=>r.push(`/character/${final.id}`))}
return <Layout><div className="wizard"><aside className="wizardNav"><div className="eyebrow">CHARACTER CREATION</div>{['Identity','Characteristics','Skills','Equipment','Starting Money','Review'].map((x,i)=><div className={i===step?'wizardItem active':'wizardItem'} key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</div>)}</aside><section className="builder panel">
{step===0&&<><div className="eyebrow">01 // IDENTITY</div><h1>Identify your spacer.</h1><label>CHARACTER NAME<input autoFocus value={c.name} onChange={e=>setC({...c,name:e.target.value})} placeholder="Designation"/></label><div className="builderActions"><button className="primary" disabled={!c.name.trim()} onClick={()=>setStep(1)}>CONTINUE →</button></div></>}
{step===1&&<><div className="eyebrow">02 // CHARACTERISTICS</div><h1>Generate characteristics.</h1><p>Roll a 6-sided die and distribute the number among the five characteristics. No characteristic may go higher than 2. Instead of rolling, you may take 4.</p><div className="rollRow"><button className="primary" onClick={roll}>ROLL D6</button><button className="secondary" onClick={take4}>TAKE 4</button><div className="pool">POOL <b>{pool??'—'}</b> / ALLOCATED <b>{total}</b></div></div><div className="grid five">{CHARACTERISTICS.map(k=><div className="stat" key={k}><span>{k}</span><b>{c.characteristics[k]}</b><div className="smallActions"><button onClick={()=>dist(k,-1)}>−</button><button onClick={()=>dist(k,1)}>+</button></div></div>)}</div><div className="derived">STAMINA <b>{8+c.characteristics.Hardiness}</b> · SPEED <b>{5+c.characteristics.Agility}m</b></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(0)}>← BACK</button><button className="primary" onClick={continueCharacteristics}>CONTINUE →</button></div></>}
{step===2&&<><div className="eyebrow">03 // SKILLS</div><h1>Train your skills.</h1><p>Choose 5 skills at 2. Choose one more skill at 3 and one more skill at 1. Then choose {extra} additional skill{extra===1?'':'s'} at 3. Skills can never be more than 5.</p><div className="skillCounts"><span>2: {at2}/5</span><span>3: {at3}/{1+extra}</span><span>1: {at1}/1</span></div><div className="skillTable">{SKILLS.map(s=><div className="skillRow" key={s}><span>{s}</span><div><button onClick={()=>setSkill(s,c.skills[s]-1)}>−</button><b>{c.skills[s]}</b><button onClick={()=>setSkill(s,c.skills[s]+1)}>+</button></div></div>)}</div><div className="builderActions"><button className="secondary" onClick={()=>setStep(1)}>← BACK</button><button className="primary" onClick={continueSkills}>CONTINUE →</button></div></>}
{step===3&&<><div className="eyebrow">04 // EQUIPMENT</div><h1>Choose equipment.</h1><p>You have 2KCr to spend. You cannot choose equipment of rarity higher than 3. Anything left can be added to starting money.</p><div className="budget">REMAINING <b>{c.equipmentCredits.toLocaleString()}Cr</b></div><input placeholder="SEARCH EQUIPMENT" value={search} onChange={e=>setSearch(e.target.value)}/><div className="equipmentChooser"><div className="equipmentList">{equip.map(e=><div className="equipmentRow" key={e.name}><div><b>{e.name}</b><span>{e.category} · Rarity {e.rarity} · {e.properties}</span><small>{e.details}</small></div><div className="equipmentBuy"><strong>{e.cost?.toLocaleString()}Cr</strong><button disabled={e.cost===null||e.cost>c.equipmentCredits} onClick={()=>addEquipment(e.name)}>ADD</button></div></div>)}</div><aside className="selectedEquipment"><h2>SELECTED EQUIPMENT</h2>{c.equipment.length===0?<p className="muted">Nothing purchased yet.</p>:c.equipment.map(item=>{const e=EQUIPMENT.find(x=>x.name===item.name);return <article className="selectedCard" key={item.id}><div className="selectedHead"><b>{item.name}</b><button className="secondary" onClick={()=>undoEquipment(item.id)}>UNDO</button></div>{e&&<><span>{e.category} · Rarity {e.rarity} · {e.cost?.toLocaleString()}Cr</span>{e.properties&&<p><strong>Properties:</strong> {e.properties}</p>}{e.details&&<p><strong>Details:</strong> {e.details}</p>}</>}</article>})}</aside></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(2)}>← BACK</button><button className="primary" onClick={()=>setStep(4)}>CONTINUE →</button></div></>}
{step===4&&<><div className="eyebrow">05 // STARTING MONEY</div><h1>Roll starting money.</h1><p>Everyone starts with 1d6 × 1000Cr. This is separate from the money spent on equipment.</p><div className="moneyRoll"><b>{startingMoney===null?'—':startingMoney.toLocaleString()+'Cr'}</b><button className="primary" onClick={()=>setStartingMoney((Math.floor(Math.random()*6)+1)*1000)}>ROLL 1D6 × 1000</button></div><div className="budget">LEFT FROM EQUIPMENT <b>{c.equipmentCredits.toLocaleString()}Cr</b></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(3)}>← BACK</button><button className="primary" disabled={startingMoney===null} onClick={()=>setStep(5)}>REVIEW →</button></div></>}
{step===5&&<><div className="eyebrow">06 // REVIEW</div><h1>{c.name}</h1><div className="grid four"><div className="stat"><span>STAMINA</span><b>{8+c.characteristics.Hardiness}</b></div><div className="stat"><span>SPEED</span><b>{5+c.characteristics.Agility}m</b></div><div className="stat"><span>LUCK</span><b>1</b></div><div className="stat"><span>STARTING MONEY</span><b>{startingMoney?.toLocaleString()}Cr</b></div></div><div className="panelInner"><h3>Characteristics</h3>{CHARACTERISTICS.map(k=><div className="line" key={k}><span>{k}</span><b>{c.characteristics[k]}</b></div>)}<h3>Skills</h3>{SKILLS.filter(s=>c.skills[s]>0).map(s=><div className="line" key={s}><span>{s}</span><b>{c.skills[s]}</b></div>)}<h3>Equipment</h3>{c.equipment.length?c.equipment.map(e=><div className="line" key={e.id}><span>{e.name} × {e.quantity}</span><b>{e.cost.toLocaleString()}Cr</b></div>):<div className="muted">No equipment selected.</div>}</div><div className="builderActions"><button className="secondary" onClick={()=>setStep(4)}>← BACK</button><button className="primary" onClick={finish}>ENTER GAME →</button></div></>}
{popup&&<div className="popupBackdrop" onClick={()=>setPopup(null)}><div className="popupCard" onClick={e=>e.stopPropagation()}><div className="popupHeader"><div><span>CREATION VALIDATION</span><h3>{popup.title}</h3></div><button className="popupClose" onClick={()=>setPopup(null)}>×</button></div><div className="popupBody">{popup.body}</div><div className="popupFooter"><button className="popupOk" onClick={()=>setPopup(null)}>UNDERSTOOD</button></div></div></div>}
<style jsx>{`.equipmentChooser{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.8fr);gap:18px;align-items:start;margin-top:12px}.selectedEquipment{border:1px solid var(--border);background:rgba(7,14,23,.78);padding:15px;position:sticky;top:16px;max-height:60vh;overflow:auto}.selectedEquipment h2{margin:0 0 12px;font:700 12px 'Orbitron',sans-serif;letter-spacing:1px;color:var(--blue-bright)}.selectedCard{border:1px solid #294157;background:linear-gradient(180deg,#101d2a,#0a111a);padding:12px;margin-bottom:10px}.selectedHead{display:flex;justify-content:space-between;align-items:center;gap:10px}.selectedHead b{font:700 12px 'Orbitron',sans-serif;color:#dff4ff}.selectedHead button{padding:6px 10px;font-size:8px}.selectedCard span{display:block;color:var(--muted);font-size:9px;margin-top:6px}.selectedCard p{font-size:10px;line-height:1.45;color:#c8d8e5;margin:8px 0 0}.selectedCard strong{color:#8fb8d3}.popupBackdrop{position:fixed;inset:0;z-index:1000;background:rgba(2,7,12,.78);backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center;padding:20px}.popupCard{width:min(520px,calc(100vw - 40px));background:linear-gradient(180deg,#142334,#0a111a);border:1px solid #35516d;box-shadow:0 24px 80px rgba(0,0,0,.65),0 0 35px rgba(64,154,220,.12);border-radius:6px;overflow:hidden}.popupHeader{display:flex;justify-content:space-between;align-items:center;padding:14px 18px;border-bottom:1px solid #294157}.popupHeader h3{margin:3px 0 0;font:700 17px 'Orbitron',sans-serif}.popupHeader span{color:var(--muted);font:8px 'Orbitron',sans-serif;letter-spacing:2px}.popupBody{padding:22px;white-space:pre-line;line-height:1.6;color:#dceaf4}.popupClose{background:none;border:1px solid #35516d;color:var(--muted);width:30px;height:30px;cursor:pointer}.popupFooter{padding:12px 18px;border-top:1px solid rgba(100,130,160,.15);text-align:right}.popupOk{padding:8px 22px;background:#12334a;border:1px solid #39739a;color:#dff4ff;cursor:pointer;font:9px 'Orbitron',sans-serif}@media(max-width:900px){.equipmentChooser{grid-template-columns:1fr}.selectedEquipment{position:static;max-height:none}}`}</style>
</section></div></Layout>}
