import {useState} from 'react'; import {useRouter} from 'next/router'; import Layout from '../../components/Layout'; import {newCharacter,recalc,characteristicTotal,creationSkillRequirementOk} from '../../lib/rules'; import {CHARACTERISTICS,SKILLS,type Characteristic,type SkillName} from '../../lib/types'; import {saveCharacter} from '../../lib/storage'; import {EQUIPMENT} from '../../data/equipment';
export default function Create(){const r=useRouter();const [c,setC]=useState(newCharacter());const [step,setStep]=useState(0);const [pool,setPool]=useState<number|null>(null);const [startingMoney,setStartingMoney]=useState<number|null>(null);const [search,setSearch]=useState('');const [popup,setPopup]=useState<{title:string;body:string}|null>(null);
const total=characteristicTotal(c.characteristics);const extra=Math.max(0,6-total);const skillVals=Object.values(c.skills);const at2=skillVals.filter(v=>v===2).length;const at3=skillVals.filter(v=>v===3).length;const at1=skillVals.filter(v=>v===1).length;const skillValid=creationSkillRequirementOk(c);
const equip=EQUIPMENT.filter(e=>e.name.toLowerCase().includes(search.toLowerCase())&&e.cost!==null&&e.rarity!==null&&e.rarity<=3);
function update(next:any){setC(recalc(next))}
function roll(){setPool(Math.floor(Math.random()*6)+1);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function take4(){setPool(4);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function dist(k:Characteristic,d:number){const v=c.characteristics[k];const sum=characteristicTotal(c.characteristics);if(d>0&&(pool===null||sum>=pool||v>=2))return;if(d<0&&v<=0)return;update({...c,characteristics:{...c.characteristics,[k]:v+d}})}
function setSkill(s:SkillName,v:number){update({...c,skills:{...c.skills,[s]:Math.max(0,Math.min(5,v))}})}
function addEquipment(name:string){const e=EQUIPMENT.find(x=>x.name===name);if(!e||e.cost===null)return;if(c.equipmentCredits<e.cost)return;update({...c,equipmentCredits:c.equipmentCredits-e.cost,equipment:[...c.equipment,{id:crypto.randomUUID(),name:e.name,quantity:1,cost:e.cost}]})}
function undoEquipment(id:string){const item=c.equipment.find(e=>e.id===id);if(!item)return;update({...c,equipmentCredits:c.equipmentCredits+item.cost,equipment:c.equipment.filter(e=>e.id!==id)})}
function continueSkills(){if(skillValid){setStep(3);return}const problems:string[]=[];if(at2!==5)problems.push(`You need exactly 5 skills at 2 (currently ${at2}).`);if(at3!==1+extra)problems.push(`You need exactly ${1+extra} skill${1+extra===1?'':'s'} at 3 (currently ${at3}).`);if(at1!==1)problems.push(`You need exactly 1 skill at 1 (currently ${at1}).`);setPopup({title:'SKILL SELECTION INCOMPLETE',body:problems.join('\n')});}
function continueCharacteristics(){if(pool!==null&&total===pool){setStep(2);return}setPopup({title:'CHARACTERISTICS INCOMPLETE',body:pool===null?'Roll the D6 or choose TAKE 4 before continuing.':`You must allocate the entire pool. Pool: ${pool}. Allocated: ${total}.`});}
function finish(){if(startingMoney===null)return;const final={...c,currentStamina:c.stamina,credits:startingMoney+c.equipmentCredits};saveCharacter(final).then(()=>r.push(`/character/${final.id}`))}
return <Layout><div className="wizard"><aside className="wizardNav"><div className="eyebrow">CHARACTER CREATION</div>{['Identity','Characteristics','Skills','Equipment','Starting Money','Review'].map((x,i)=><div className={i===step?'wizardItem active':'wizardItem'} key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</div>)}</aside><section className="builder panel">
{step===0&&<><div className="eyebrow">01 // IDENTITY</div><h1>Identify your spacer.</h1><label>CHARACTER NAME<input autoFocus value={c.name} onChange={e=>setC({...c,name:e.target.value})} placeholder="Designation"/></label><div className="builderActions"><button className="primary" disabled={!c.name.trim()} onClick={()=>setStep(1)}>CONTINUE →</button></div></>}
{step===1&&<><div className="eyebrow">02 // CHARACTERISTICS</div><h1>Generate characteristics.</h1><p>Roll a 6-sided die and distribute the number among the five characteristics. No characteristic may go higher than 2. Instead of rolling, you may take 4.</p><div className="rollRow"><button className="primary" onClick={roll}>ROLL D6</button><button className="secondary" onClick={take4}>TAKE 4</button><div className="pool">POOL <b>{pool??'—'}</b> / ALLOCATED <b>{total}</b></div></div><div className="grid five">{CHARACTERISTICS.map(k=><div className="stat" key={k}><span>{k}</span><b>{c.characteristics[k]}</b><div className="smallActions"><button onClick={()=>dist(k,-1)}>−</button><button onClick={()=>dist(k,1)}>+</button></div></div>)}</div><div className="derived">STAMINA <b>{8+c.characteristics.Hardiness}</b> · SPEED <b>{5+c.characteristics.Agility}m</b></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(0)}>← BACK</button><button className="primary" onClick={continueCharacteristics}>CONTINUE →</button></div></>}
{step===2&&<><div className="eyebrow">03 // SKILLS</div><h1>Train your skills.</h1><p>Choose 5 skills at 2. Choose one more skill at 3 and one more skill at 1. Then choose {extra} additional skill{extra===1?'':'s'} at 0. Skills cannot exceed 5. A skill at 3 must be a skill you have at 2.</p><div className="grid two"><div className="skillList">{SKILLS.map(s=><label key={s}><span>{s}</span><input type="number" min={0} max={5} value={c.skills[s]} onChange={e=>setSkill(s,Number(e.target.value))}/></label>)}</div><aside className="helpPanel"><h3>Creation rules</h3><p>You must choose exactly five skills at value 2. One skill at 3 (which must also be one of the 2s). One skill at 1. If you took less than 6 points in characteristics, you gain extra free skill points as shown above.</p></aside></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(1)}>← BACK</button><button className="primary" onClick={continueSkills}>CONTINUE →</button></div></>}
{step===3&&<><div className="eyebrow">04 // EQUIPMENT</div><h1>Choose equipment.</h1><p>You have 2KCr to spend. You cannot choose equipment of rarity higher than 3. Anything left can be added to starting money.</p><div className="equipmentChooser"><div className="chooser"><input placeholder="Search equipment" value={search} onChange={e=>setSearch(e.target.value)}/><div className="results">{equip.map(e=>{const cap=e.details?.split(';').map(x=>x.trim()).find(x=>/^magazine\b/i.test(x));return <div key={e.name} className="result"><div><b>{e.name}</b><div className="muted">{e.category} · {e.cost}Cr</div></div><div><button className="secondary" onClick={()=>addEquipment(e.name)}>ADD</button></div></div})}</div></div><aside className="selectedEquipment"><h3>Selected</h3><div className="selectedList">{c.equipment.map(e=><div key={e.id} className="selected"><div><b>{e.name}</b><div className="muted">{e.quantity} · {e.cost}Cr</div></div><div><button className="secondary" onClick={()=>undoEquipment(e.id)}>REMOVE</button></div></div>)}</div></aside></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(2)}>← BACK</button><button className="primary" onClick={()=>setStep(4)}>CONTINUE →</button></div></>}
{step===4&&<><div className="eyebrow">05 // STARTING MONEY</div><h1>Roll starting money.</h1><p>Everyone starts with 1d6 × 1000Cr. This is separate from the money spent on equipment.</p><div className="rollRow"><button className="primary" onClick={()=>setStartingMoney((Math.floor(Math.random()*6)+1)*1000)}>ROLL 1D6</button><div className="pool">STARTING MONEY <b>{startingMoney??'—'}</b></div></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(3)}>← BACK</button><button className="primary" onClick={finish}>FINISH →</button></div></>}
{step===5&&<><div className="eyebrow">06 // REVIEW</div><p style={{marginBottom:8}}><a href="https://tabletopnonsenseverse.myshopify.com/products/astrovoyage" target="_blank" rel="noopener noreferrer">Get the free version of the game here.</a></p><h1>{c.name}</h1><div className="grid four"><div className="stat"><span>STAMINA</span><b>{8+c.characteristics.Hardiness}</b></div><div className="stat"><span>LUCK</span><b>{c.luck} / 6</b></div><div className="stat"><span>SPEED</span><b>{5+c.characteristics.Agility}m</b></div><div className="stat"><span>ARMOUR</span><b>{c.armourValue}</b></div></div><div className="grid four"><div className="panel"><h3>CHARACTERISTICS</h3><div className="chars">{CHARACTERISTICS.map(x=><div key={x} className="char"><b>{c.characteristics[x]}</b><span>{x}</span></div>)}</div></div><div className="panel"><h3>SKILLS</h3><div className="skills">{SKILLS.map(s=><div key={s} className="skill"><span>{s}</span><b>{c.skills[s]}</b></div>)}</div></div><div className="panel"><h3>INVENTORY</h3><div>{c.equipment.map(e=><div key={e.id} className="item"><b>{e.name}</b><div className="muted">{e.quantity} · {e.cost}Cr</div></div>)}</div></div><div className="panel"><h3>RESOURCES</h3><div className="resourceRow"><div>CREDITS<b>{c.credits}</b></div><div>STARTING MONEY<b>{startingMoney}</b></div></div></div></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(4)}>← BACK</button><button className="primary" onClick={()=>{saveCharacter({...c,currentStamina:8+c.characteristics.Hardiness,credits:(startingMoney??0)+c.equipmentCredits}).then(()=>r.push(`/character/${c.id}`))}}>SAVE CHARACTER</button></div></>}
{popup&&<div className="popupBackdrop" onClick={()=>setPopup(null)}><div className="popupCard" onClick={e=>e.stopPropagation()}><div className="popupHeader"><div><span>CREATION VALIDATION</span><h3>{popup.title}</h3></div><div className="popupClose" onClick={()=>setPopup(null)}>✕</div></div><div className="popupBody"><pre>{popup.body}</pre></div></div></div>}
<style jsx>{`.equipmentChooser{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(280px,.8fr);gap:18px;align-items:start;margin-top:12px}.selectedEquipment{border:1px solid var(--border);background:var(--panel);padding:10px}.selectedList{display:grid;gap:8px;max-height:320px;overflow:auto}.results{display:grid;gap:8px;max-height:360px;overflow:auto}.result{display:flex;justify-content:space-between;align-items:center}.rollRow{display:flex;gap:8px;align-items:center}.smallActions{display:flex;gap:6px}.grid.four{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid.two{display:grid;grid-template-columns:1fr 360px;gap:18px}.grid.five{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.builderActions{display:flex;gap:8px;margin-top:12px}.muted{color:var(--muted)}.wizard{display:flex;gap:18px}.wizardNav{width:200px}.wizardItem{padding:12px;border:1px solid var(--border);margin-bottom:8px;background:var(--panel);display:flex;gap:12px;align-items:center}.wizardItem b{background:#071b26;color:#b9eefb;padding:6px 8px;font:12px 'Orbitron',sans-serif;border-radius:4px}.wizardItem.active{box-shadow:inset 0 0 0 2px #fff}.builder{flex:1}.eyebrow{font-size:10px;letter-spacing:2px;color:var(--muted)}.panel{background:var(--panel);padding:18px;border:1px solid var(--border)}.stat{padding:8px;border:1px solid var(--border)}.chars{display:grid;grid-template-columns:repeat(5,1fr)}.char{padding:8px;text-align:center}`}</style>
</section></div></Layout>}
