import {useMemo,useState} from 'react'; import {useRouter} from 'next/router'; import Layout from '../../components/Layout'; import {newCharacter,recalc,characteristicTotal,creationSkillRequirementOk} from '../../lib/rules'; import {CHARACTERISTICS,SKILLS,type Characteristic,type SkillName} from '../../lib/types'; import {saveCharacter} from '../../lib/storage'; import {EQUIPMENT} from '../../data/equipment';
export default function Create(){const r=useRouter();const [c,setC]=useState(newCharacter());const [step,setStep]=useState(0);const [pool,setPool]=useState<number|null>(null);const [startingMoney,setStartingMoney]=useState<number|null>(null);const [search,setSearch]=useState('');
const total=characteristicTotal(c.characteristics);const extra=Math.max(0,6-total);const skillVals=Object.values(c.skills);const at2=skillVals.filter(v=>v===2).length;const at3=skillVals.filter(v=>v===3).length;const at1=skillVals.filter(v=>v===1).length;const skillValid=creationSkillRequirementOk(c);
const equip=EQUIPMENT.filter(e=>e.name.toLowerCase().includes(search.toLowerCase())&&e.cost!==null&&e.rarity!==null&&e.rarity<=3);
function update(next:any){setC(recalc(next))}
function roll(){setPool(Math.floor(Math.random()*6)+1);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function take4(){setPool(4);update({...c,characteristics:Object.fromEntries(CHARACTERISTICS.map(k=>[k,0]))})}
function dist(k:Characteristic,d:number){const v=c.characteristics[k];const sum=characteristicTotal(c.characteristics);if(d>0&&(pool===null||sum>=pool||v>=2))return;if(d<0&&v<=0)return;update({...c,characteristics:{...c.characteristics,[k]:v+d}})}
function setSkill(s:SkillName,v:number){update({...c,skills:{...c.skills,[s]:Math.max(0,Math.min(5,v))}})}
function addEquipment(name:string){const e=EQUIPMENT.find(x=>x.name===name);if(!e||e.cost===null)return;if(c.equipmentCredits<e.cost)return;update({...c,equipmentCredits:c.equipmentCredits-e.cost,equipment:[...c.equipment,{id:crypto.randomUUID(),name:e.name,quantity:1,cost:e.cost}]})}
function finish(){if(startingMoney===null)return;const final={...c,credits:startingMoney+c.equipmentCredits};saveCharacter(final).then(()=>r.push(`/character/${final.id}`))}
return <Layout><div className="wizard"><aside className="wizardNav"><div className="eyebrow">CHARACTER CREATION</div>{['Identity','Characteristics','Skills','Equipment','Starting Money','Review'].map((x,i)=><div className={i===step?'wizardItem active':'wizardItem'} key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</div>)}</aside><section className="builder panel">
{step===0&&<><div className="eyebrow">01 // IDENTITY</div><h1>Identify your spacer.</h1><label>CHARACTER NAME<input autoFocus value={c.name} onChange={e=>setC({...c,name:e.target.value})} placeholder="Designation"/></label><div className="builderActions"><button className="primary" disabled={!c.name.trim()} onClick={()=>setStep(1)}>CONTINUE →</button></div></>}
{step===1&&<><div className="eyebrow">02 // CHARACTERISTICS</div><h1>Generate characteristics.</h1><p>Roll a 6-sided die and distribute the number among the five characteristics. No characteristic may go higher than 2. Instead of rolling, you may take 4.</p><div className="rollRow"><button className="primary" onClick={roll}>ROLL D6</button><button className="secondary" onClick={take4}>TAKE 4</button><div className="pool">POOL <b>{pool??'—'}</b> / ALLOCATED <b>{total}</b></div></div><div className="grid five">{CHARACTERISTICS.map(k=><div className="stat" key={k}><span>{k}</span><b>{c.characteristics[k]}</b><div className="smallActions"><button onClick={()=>dist(k,-1)}>−</button><button onClick={()=>dist(k,1)}>+</button></div></div>)}</div><div className="derived">STAMINA <b>{8+c.characteristics.Hardiness}</b> · SPEED <b>{5+c.characteristics.Agility}m</b></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(0)}>← BACK</button><button className="primary" disabled={pool===null||total!==pool} onClick={()=>setStep(2)}>CONTINUE →</button></div></>}
{step===2&&<><div className="eyebrow">03 // SKILLS</div><h1>Train your skills.</h1><p>Choose 5 skills at 2. Choose one more skill at 3 and one more skill at 1. Then choose {extra} additional skill{extra===1?'':'s'} at 3. Skills can never be more than 5.</p><div className="skillCounts"><span>2: {at2}/5</span><span>3: {at3}/{1+extra}</span><span>1: {at1}/1</span></div><div className="skillTable">{SKILLS.map(s=><div className="skillRow" key={s}><span>{s}</span><div><button onClick={()=>setSkill(s,c.skills[s]-1)}>−</button><b>{c.skills[s]}</b><button onClick={()=>setSkill(s,c.skills[s]+1)}>+</button></div></div>)}</div><div className="builderActions"><button className="secondary" onClick={()=>setStep(1)}>← BACK</button><button className="primary" disabled={!skillValid} onClick={()=>setStep(3)}>CONTINUE →</button></div></>}
{step===3&&<><div className="eyebrow">04 // EQUIPMENT</div><h1>Choose equipment.</h1><p>You have 2KCr to spend. You cannot choose equipment of rarity higher than 3. Anything left can be added to starting money.</p><div className="budget">REMAINING <b>{c.equipmentCredits.toLocaleString()}Cr</b></div><input placeholder="SEARCH EQUIPMENT" value={search} onChange={e=>setSearch(e.target.value)}/><div className="equipmentList">{equip.map(e=><div className="equipmentRow" key={e.name}><div><b>{e.name}</b><span>{e.category} · Rarity {e.rarity} · {e.properties}</span><small>{e.details}</small></div><div className="equipmentBuy"><strong>{e.cost?.toLocaleString()}Cr</strong><button disabled={e.cost===null||e.cost>c.equipmentCredits} onClick={()=>addEquipment(e.name)}>ADD</button></div></div>)}</div><div className="builderActions"><button className="secondary" onClick={()=>setStep(2)}>← BACK</button><button className="primary" onClick={()=>setStep(4)}>CONTINUE →</button></div></>}
{step===4&&<><div className="eyebrow">05 // STARTING MONEY</div><h1>Roll starting money.</h1><p>Everyone starts with 1d6 × 1000Cr. This is separate from the money spent on equipment.</p><div className="moneyRoll"><b>{startingMoney===null?'—':startingMoney.toLocaleString()+'Cr'}</b><button className="primary" onClick={()=>setStartingMoney((Math.floor(Math.random()*6)+1)*1000)}>ROLL 1D6 × 1000</button></div><div className="budget">LEFT FROM EQUIPMENT <b>{c.equipmentCredits.toLocaleString()}Cr</b></div><div className="builderActions"><button className="secondary" onClick={()=>setStep(3)}>← BACK</button><button className="primary" disabled={startingMoney===null} onClick={()=>setStep(5)}>REVIEW →</button></div></>}
{step===5&&<><div className="eyebrow">06 // REVIEW</div><h1>{c.name}</h1><div className="grid four"><div className="stat"><span>STAMINA</span><b>{8+c.characteristics.Hardiness}</b></div><div className="stat"><span>SPEED</span><b>{5+c.characteristics.Agility}m</b></div><div className="stat"><span>LUCK</span><b>1</b></div><div className="stat"><span>STARTING MONEY</span><b>{startingMoney?.toLocaleString()}Cr</b></div></div><div className="panelInner"><h3>Characteristics</h3>{CHARACTERISTICS.map(k=><div className="line" key={k}><span>{k}</span><b>{c.characteristics[k]}</b></div>)}<h3>Skills</h3>{SKILLS.filter(s=>c.skills[s]>0).map(s=><div className="line" key={s}><span>{s}</span><b>{c.skills[s]}</b></div>)}<h3>Equipment</h3>{c.equipment.length?c.equipment.map(e=><div className="line" key={e.id}><span>{e.name} × {e.quantity}</span><b>{e.cost.toLocaleString()}Cr</b></div>):<div className="muted">No equipment selected.</div>}</div><div className="builderActions"><button className="secondary" onClick={()=>setStep(4)}>← BACK</button><button className="primary" onClick={finish}>ENTER GAME →</button></div></>}
</section></div></Layout>}
