import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Layout from '../../../components/Layout'
import type { Character, EquipmentEntry } from '../../../lib/types'
import { loadCharacter, saveCharacter } from '../../../lib/storage'
import { EQUIPMENT } from '../../../data/equipment'
import { WEAPON_ACTIONS } from '../../../data/weaponPresentation'

const numberOr=(v:string,f:number)=>{const n=Number(v);return Number.isFinite(n)?n:f}
const stackLimit=(carry?:string)=>{const m=carry?.match(/(\d+)\s*\/\s*slot/i);return m?Math.max(1,Number(m[1])):1}
const magazineCapacity=(d:string)=>{const m=d.split(';').map(x=>x.trim()).find(x=>/^magazine\b/i.test(x));if(!m)return null;const n=Number(m.replace(/^magazine\s*/i,''));return Number.isFinite(n)?n:null}
const slotsFor=(e:EquipmentEntry)=>Math.ceil(Math.max(1,e.quantity)/stackLimit(e.carry??EQUIPMENT.find(x=>x.name===e.name)?.carry))

export default function InventoryPage(){
 const r=useRouter();const[c,setC]=useState<Character|null>(null)
 useEffect(()=>{if(r.isReady)loadCharacter(String(r.query.id)).then(x=>x&&setC(x))},[r.isReady,r.query.id])
 if(!c)return <Layout><div className="panel">LOADING INVENTORY...</div></Layout>
 const save=(n:Character)=>{setC(n);void saveCharacter(n)}
 const capacity=Math.max(0,c.carryCapacity??10)
 const equipped=c.equipment.map((e,i)=>({...e,_i:i})).filter(e=>(e.location??'equipped')==='equipped')
 const storage=c.equipment.map((e,i)=>({...e,_i:i})).filter(e=>e.location==='storage')
 const equippedSlots=equipped.reduce((sum,e)=>sum+slotsFor(e),0)
 const addEquipment=(name:string)=>{const x=EQUIPMENT.find(e=>e.name===name);if(!x||x.cost===null)return;const cap=magazineCapacity(x.details);const entry:EquipmentEntry={id:crypto.randomUUID(),name:x.name,quantity:1,cost:x.cost,properties:x.properties||'—',rarity:x.rarity,carry:x.carry,details:x.details,location:'storage',...(cap!==null?{currentMagazine:cap}:{})};save({...c,equipment:[...c.equipment,entry]})}
 const update=(index:number,p:Partial<EquipmentEntry>)=>save({...c,equipment:c.equipment.map((e,i)=>i===index?{...e,...p}:e)})
 const remove=(index:number)=>save({...c,equipment:c.equipment.filter((_,i)=>i!==index)})
 const move=(index:number,location:'equipped'|'storage')=>{if(location==='equipped'){const item=c.equipment[index];if(!item)return;const needed=slotsFor(item);if(equippedSlots+needed>capacity){window.alert(`Not enough carry capacity. ${equippedSlots}/${capacity} slots are used.`);return}}update(index,{location})}
 const changeQuantity=(index:number,value:number)=>{const e=c.equipment[index];if(!e)return;const limit=stackLimit(e.carry??EQUIPMENT.find(x=>x.name===e.name)?.carry);update(index,{quantity:Math.max(1,Math.min(limit,value))})}
 const card=(item:EquipmentEntry & {_i:number})=>{const d=EQUIPMENT.find(x=>x.name===item.name);if(!d)return null;const limit=stackLimit(item.carry??d.carry);const isEquipped=item.location!=='storage';const mag=magazineCapacity(item.details??d.details);return <article className="equipmentCard" key={item.id}><div className="cardHead"><div><h3>{item.name}</h3><div className="meta">{d.category} · {isEquipped?'EQUIPPED':'STORAGE'}</div></div><button className="danger" onClick={()=>remove(item._i)}>REMOVE</button></div><div className="fields"><label>Properties<input value={item.properties??d.properties??''} onChange={e=>update(item._i,{properties:e.target.value})}/></label><label>Quantity<input type="number" min={1} max={limit} value={item.quantity} onChange={e=>changeQuantity(item._i,numberOr(e.target.value,item.quantity))}/><small>MAX {limit}/SLOT</small></label></div>{mag!==null&&<label className="mag">CURRENT MAGAZINE<input type="number" min={0} max={mag} value={item.currentMagazine??mag} onChange={e=>update(item._i,{currentMagazine:Math.max(0,Math.min(mag,numberOr(e.target.value,mag)))})}/></label>}<div className="equipmentDetails">{(item.details??d.details).split(';').map(x=>x.trim()).filter(Boolean).map(x=><div className="equipmentRule" key={x}>{x}</div>)}</div><button className="moveButton" onClick={()=>move(item._i,isEquipped?'storage':'equipped')}>{isEquipped?'UNEQUIP':'EQUIP'}</button></article>}
 return <Layout><div className="activeTop"><div><div className="eyebrow">ACTIVE PERSONNEL // PAGE 02</div><h1>{c.name||'UNNAMED'} — INVENTORY</h1></div><div className="pageTabs"><Link href={`/character/${c.id}`}>PAGE 01</Link><span className="active">PAGE 02 // INVENTORY</span></div></div><div className="panel inventoryBar"><strong>EQUIPPED: {equippedSlots} / {capacity} SLOTS</strong><select defaultValue="" onChange={e=>{if(e.target.value){addEquipment(e.target.value);e.currentTarget.value=''}}}><option value="">ADD EQUIPMENT TO STORAGE...</option>{EQUIPMENT.map(x=><option key={x.name} value={x.name} disabled={x.cost===null}>{x.name}</option>)}</select></div><section><h2>EQUIPPED</h2><div className="equipmentGrid">{equipped.length?equipped.map(card):<p className="muted">Nothing equipped.</p>}</div></section><section><h2>STORAGE</h2><div className="equipmentGrid">{storage.length?storage.map(card):<p className="muted">Storage is empty.</p>}</div></section><style jsx>{`.pageTabs{display:flex;gap:8px;align-items:center}.pageTabs a,.pageTabs span{padding:8px 12px;border:1px solid var(--border);font:9px 'Orbitron',sans-serif;letter-spacing:1px;text-decoration:none}.pageTabs a{color:var(--muted)}.pageTabs .active{color:var(--blue-bright);border-color:var(--blue)}.inventoryBar{display:flex;justify-content:space-between;align-items:center;gap:15px}.inventoryBar select{width:auto;min-width:260px;margin:0}.equipmentGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-bottom:18px}.equipmentCard{border:1px solid var(--border);background:rgba(7,14,23,.78);padding:15px}.cardHead{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.cardHead h3{margin:0;font:600 14px 'Orbitron',sans-serif;color:#e7f1fc}.meta{margin-top:5px;color:var(--muted);font-size:10px}.fields{display:grid;grid-template-columns:1fr 120px;gap:10px}.fields label,.mag{font-size:9px;color:var(--muted)}.fields input,.mag input{width:100%;margin-top:5px}.fields small{display:block;margin-top:3px;font-size:8px}.mag{display:block;margin-top:10px}.equipmentDetails{margin-top:12px;border-top:1px solid #1d2d42;padding-top:8px}.equipmentRule{font-size:12px;line-height:1.4;padding:4px 0;border-bottom:1px solid rgba(100,130,160,.1)}.moveButton{width:100%;margin-top:12px;padding:9px;background:#10283a;border:1px solid #39739a;color:#dff4ff;font:9px 'Orbitron',sans-serif;letter-spacing:1px;cursor:pointer}.moveButton:hover{background:#174562}section h2{font:600 12px 'Orbitron',sans-serif;letter-spacing:2px;color:var(--blue-bright);margin:20px 0 10px}@media(max-width:800px){.equipmentGrid{grid-template-columns:1fr}.inventoryBar{align-items:stretch;flex-direction:column}.inventoryBar select{width:100%}.fields{grid-template-columns:1fr}.activeTop{align-items:flex-start;flex-direction:column}}`}</style></Layout>
}
