import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Link from 'next/link'
import Layout from '../../../components/Layout'
import type { Character, EquipmentEntry } from '../../../lib/types'
import { loadCharacter, saveCharacter } from '../../../lib/storage'
import { EQUIPMENT } from '../../../data/equipment'
import { WEAPON_ACTIONS } from '../../../data/weaponPresentation'

const numberOr=(v:string,f:number)=>{const n=Number(v);return Number.isFinite(n)?n:f}
const stackLimit=(carry?:string)=>{const m=carry?.match(/(\d+)\s*\/\s*slot/i);return m?Math.max(1,Number(m[1])):1}
const magazineCapacity=(d:string)=>{const m=d.split(';').map(x=>x.trim()).find(x=>/^magazine\b/i.test(x));if(!m)return null;const n=Number(m.replace(/^magazine\s*/i,''));return Number.isFinite(n)?n:null}
const defaultAttackCheck=(name:string,details:string)=>{const a=WEAPON_ACTIONS[name]?.find(x=>/single shot|^shot$/i.test(x.title))||WEAPON_ACTIONS[name]?.[0];return a?.check||details.split(';').map(x=>x.trim()).find(x=>/Weapon,|^\d+d\d+/i.test(x))||''}
const slotsFor=(e:EquipmentEntry)=>Math.ceil(Math.max(1,e.quantity)/stackLimit(e.carry??EQUIPMENT.find(x=>x.name===e.name)?.carry))

type Popup={title:string;body:string}|null

export default function InventoryPage(){
 const r=useRouter();const[c,setC]=useState<Character|null>(null);const[popup,setPopup]=useState<Popup>(null)
 useEffect(()=>{if(r.isReady)loadCharacter(String(r.query.id)).then(x=>x&&setC(x))},[r.isReady,r.query.id])
 if(!c)return <Layout><div className="panel">LOADING INVENTORY...</div></Layout>
 const save=(n:Character)=>{setC(n);void saveCharacter(n)}
 const capacity=Math.max(0,c.carryCapacity??10)
 const equipped=c.equipment.map((e,i)=>({...e,_i:i})).filter(e=>(e.location??'equipped')==='equipped')
 const storage=c.equipment.map((e,i)=>({...e,_i:i})).filter(e=>e.location==='storage')
 const equippedSlots=equipped.reduce((sum,e)=>sum+slotsFor(e),0)
 const addEquipment=(name:string)=>{const x=EQUIPMENT.find(e=>e.name===name);if(!x||x.cost===null)return;const cap=magazineCapacity(x.details);const entry:EquipmentEntry={id:crypto.randomUUID(),name:x.name,quantity:1,cost:x.cost,properties:x.properties||'—',rarity:x.rarity,carry:x.carry,details:x.details,location:'storage',...(cap!==null?{currentMagazine:cap}:{})};save({...c,equipment:[...c.equipment,entry]})}
 const move=(index:number,location:'equipped'|'storage')=>{if(location==='equipped'){const item=c.equipment[index];if(!item)return;const needed=slotsFor(item);if(equippedSlots+needed>capacity){setPopup({title:'EQUIPPED CAPACITY FULL',body:`This item needs ${needed} equipped slot${needed===1?'':'s'}, but only ${Math.max(0,capacity-equippedSlots)} are available. Unequip something first.`});return}}save({...c,equipment:c.equipment.map((e,i)=>i===index?{...e,location}:e)})}
 const update=(index:number,p:Partial<EquipmentEntry>)=>save({...c,equipment:c.equipment.map((e,i)=>i===index?{...e,...p}:e)})
 const remove=(index:number)=>save({...c,equipment:c.equipment.filter((_,i)=>i!==index)})
 const changeQuantity=(index:number,value:number)=>{const e=c.equipment[index];if(!e)return;const limit=stackLimit(e.carry??EQUIPMENT.find(x=>x.name===e.name)?.carry);if(value>limit){setPopup({title:'STACK LIMIT REACHED',body:`${e.name} allows a maximum of ${limit} item${limit===1?'':'s'} per slot. Add another stack if you need more.`});return}update(index,{quantity:Math.max(1,value)})}
 const card=(item:EquipmentEntry & {_i:number})=>{const d=EQUIPMENT.find(x=>x.name===item.name);if(!d)return null;const limit=stackLimit(item.carry??d.carry);const check=defaultAttackCheck(item.name,item.details??d.details);const isEquipped=item.location!=='storage';const description=(item.details??d.details??'').trim();return <article className="equipmentCard" key={item.id}><div className="cardHead"><button className="nameButton" onClick={()=>check&&setPopup({title:`${item.name} — Single Shot`,body:`Attack check: ${check.replace(/Weapon, /,'Weapons, ')}`})}>{item.name}</button><button className="danger" onClick={()=>remove(item._i)}>REMOVE</button></div>{description&&<div className="description"><strong>DESCRIPTION</strong><div>{description}</div></div>}<div className="meta">{d.category} · {item.carry??d.carry} · {isEquipped?'EQUIPPED':'STORAGE'}</div><div className="fields"><label>Properties<input value={item.properties??d.properties??''} onChange={e=>update(item._i,{properties:e.target.value})}/></label><label>Quantity<input type="number" min={1} max={limit} value={item.quantity} onChange={e=>changeQuantity(item._i,numberOr(e.target.value,item.quantity))}/><small>MAX {limit}/SLOT</small></label></div>{magazineCapacity(item.details??d.details)!==null&&<label className="mag">CURRENT MAGAZINE<input type="number" min={0} max={magazineCapacity(item.details??d.details)!} value={item.currentMagazine??magazineCapacity(item.details??d.details)!} onChange={e=>update(item._i,{currentMagazine:Math.max(0,Math.min(magazineCapacity(item.details??d.details)!,numberOr(e.target.value,0)))})}/></label>}<button className="moveButton" onClick={()=>move(item._i,isEquipped?'storage':'equipped')}>{isEquipped?'UNEQUIP → STORAGE':'EQUIP → EQUIPPED'}</button></article>}
 return <><style jsx global>{`.description{margin:8px 0 12px;padding:9px 11px;border-left:2px solid #39739a;background:rgba(22,45,65,.45);color:#c9d9e6;font-size:11px;line-height:1.5}.description strong{display:block;margin-bottom:4px;color:var(--muted);font:8px 'Orbitron',sans-serif;letter-spacing:1px}`}</style><Layout><div className="inventoryPage"><div className="inventoryNav"><div><div className="eyebrow">ACTIVE PERSONNEL // PAGE 02</div><h1>{c.name||'UNNAMED'} — INVENTORY</h1></div><div className="pageTabs"><Link href={`/character/${c.id}`}>PAGE 01</Link><a className="active" href={`/character/${c.id}/inventory`}>PAGE 02 // INVENTORY</a></div></div><div className="panel capacity"><strong>EQUIPPED SLOTS</strong><b>{equippedSlots} / </b><input type="number" min={0} value={capacity} onChange={e=>save({...c,carryCapacity:Math.max(0,numberOr(e.target.value,capacity))})}/><span className="muted">Storage has unlimited slots.</span><select className="addSelect" defaultValue="" onChange={e=>{if(e.target.value){addEquipment(e.target.value);e.currentTarget.value=''}}}><option value="">ADD TO STORAGE...</option>{EQUIPMENT.map(x=><option key={x.name} value={x.name} disabled={x.cost===null}>{x.name}</option>)}</select></div><div className="inventoryCols"><section className="inventorySection"><div className="sectionTitle"><h2>EQUIPPED</h2><span className="muted">{equippedSlots} / {capacity} SLOTS</span></div><div className="equipmentGrid">{equipped.length?equipped.map(card):<p className="muted">Nothing equipped.</p>}</div></section><section className="inventorySection"><div className="sectionTitle"><h2>STORAGE</h2><span className="muted">UNLIMITED</span></div><div className="equipmentGrid">{storage.length?storage.map(card):<p className="muted">Storage is empty.</p>}</div></section></div></div>{popup&&<div className="popupBackdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)setPopup(null)}}><div className="popupCard"><div className="popupHeader"><div><span>ASTROVOYAGE // FIELD DATA</span><h3>{popup.title}</h3></div><button className="popupClose" onClick={()=>setPopup(null)}>×</button></div><div className="popupBody">{popup.body}</div><div className="popupFooter"><button className="popupOk" onClick={()=>setPopup(null)}>ACKNOWLEDGE</button></div></div></div>}</Layout></> 
}
